/**
 * Auto-generated by scripts/build-config.js
 * Do not edit manually.
 */
(function (global) {
  global.TextBridgeRuntimeConfig = Object.freeze(
  {
    "oauth": {
      "clientId": "263619000588-b4kgk32oh3isjk8ovi1t15l079ict63c.apps.googleusercontent.com",
      "projectId": "textbridge-extension",
      "authUri": "https://accounts.google.com/o/oauth2/auth",
      "tokenUri": "https://oauth2.googleapis.com/token",
      "authProviderCertUrl": "https://www.googleapis.com/oauth2/v1/certs",
      "sheetsScope": "https://www.googleapis.com/auth/spreadsheets"
    },
    "endpoints": {
      "translateApiBase": "https://translate.googleapis.com",
      "translateWebBase": "https://translate.google.com",
      "dictionaryApiBase": "https://api.dictionaryapi.dev",
      "sheetsApiBase": "https://sheets.googleapis.com"
    },
    "security": {
      "requireHttps": true
    }
  }
  );
})(self);
